sudo: required

language: ruby

services:
  - docker

env:
  - UCD_STREAM=latest
  - UCD_VERSION=

before_install:
  - curl -O "https://s3.amazonaws.com/artifacts.stackinabox.io/urbancode/ibm-ucd/$UCD_STREAM.txt"
  - export UCD_VERSION=`cat latest.txt`
  - curl -O "https://s3.amazonaws.com/artifacts.stackinabox.io/urbancode/ibm-ucd/$UCD_VERSION/ibm-ucd.zip"
  - unzip -q ibm-ucd.zip -d artifacts/
  - rm -f ibm-ucd.zip
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t stackinabox/urbancode-deploy:$UCD_VERSION .

script:
  - docker push stackinabox/urbancode-deploy:$UCD_VERSION
