version: '2'
services:
  ucddb:
    image: mysql:5.6
    container_name: ucddb
    environment:
      - MYSQL_ROOT_PASSWORD=aWJtX3VjZHAK
      - MYSQL_USER=ibm_ucd
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=ibm_ucd
    ports:
      - "3306:3306"
    restart: always
  ucd:
    build:
      context: .
      args:
        ARTIFACT_DOWNLOAD_URL: http://mediahost/ibm-ucd-6.2.1.2.801550.zip
        ARTIFACT_VERSION: 6.2.1.2.801550
    image: stackinabox/urbancode-deploy:6.2.1.2.801550
    container_name: ucd
    ports:
      - "7918:7918"
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - ucddb
    environment:
      - LICENSE=accept
      - DATABASE_USER=ibm_ucd
      - DATABASE_PASS=passw0rd
      - DATABASE_NAME=ibm_ucd
      - DATABASE_PORT=3306
      - DATABASE_HOST=ucddb
      - RCL_URL=27000@rlks
